---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - /home/aidan/docker/data/heimdall:/config
    ports:
      - 82:80
      - 445:443
    restart: unless-stopped
